source 'https://rubygems.org'

gem 'thin'
gem 'sinatra'
gem 'warden'
gem 'jwt'

gem 'ohm'
gem 'ohm-validations'
gem 'ohm-contrib'
gem 'bcrypt'

gem 'pry', groups: [:development, :test]

gem 'guard-rack', group: :development

group(:test) do
  gem 'rspec'
  gem 'rspec-sane-http', github: 'botanicus/rspec-sane-http'
end
