source 'https://rubygems.org'

gem 'thin'
gem 'sinatra'
gem 'warden'
gem 'jwt'
gem 'rack-jwt-token-auth', github: 'botanicus/rack-jwt-token-auth'
gem 'rack-parse-posted-json', github: 'botanicus/rack-parse-posted-json'

gem 'ohm'
gem 'ohm-validations'
gem 'ohm-contrib'
gem 'bcrypt'

gem 'pry', groups: [:development, :test]

gem 'guard-rack', group: :development

group(:test) do
  gem 'rspec'
  gem 'rspec-sane-http', github: 'botanicus/rspec-sane-http'
end
